name: Code Quality

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    name: Quality Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check
        continue-on-error: false

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: TypeScript type checking
        run: npm run typecheck
        continue-on-error: false

      - name: Run unit tests with coverage
        run: npm run test:coverage
        continue-on-error: false

      - name: Build application
        run: npm run build
        continue-on-error: false

      - name: Check build size
        run: |
          echo "Build completed successfully!"
          echo "Build artifacts:"
          ls -la dist/
          echo "Build size:"
          du -sh dist/

  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for outdated packages
        run: npm outdated || true
